import { EventResponse } from "@/modules/portal/services/api/event.service";

export const dummyEvents: EventResponse[] = [
    {
        id: "evt-1",
        title: "HIMAIF TECH FEST 2025 – Festival Teknologi & Inovasi Mahasiswa",
        description:
            "HIMAIF Tech Fest adalah festival teknologi tahunan yang menghadirkan kompetisi coding, hackathon, seminar IT, dan pameran inovasi mahasiswa. Acara ini terbuka untuk seluruh mahasiswa informatika se-Jawa Barat dan akan menjadi wadah kolaborasi dan kreativitas generasi muda teknologi.",
        start_date: "2025-08-15",
        end_date: "2025-08-17",
        published_at: "2025-07-01T09:00:00Z",
        status: "published",
        is_implemented: false,
        slug: "himaif-tech-fest-2025",
        cover_image: null,
        carousel_images: [],
        galler_image: [],
        location: "Kampus UBSI PSDKU Sukabumi",
        time_filter: "upcoming",
    },
    {
        id: "evt-2",
        title: "Seminar Nasional: AI dan Masa Depan Industri 5.0",
        description:
            "Seminar nasional menghadirkan pembicara dari industri teknologi terkemuka untuk membahas perkembangan kecerdasan buatan dan dampaknya pada dunia kerja di era Industri 5.0. Terbuka untuk umum dengan pendaftaran gratis bagi mahasiswa UBSI.",
        start_date: "2025-07-20",
        end_date: "2025-07-20",
        published_at: "2025-06-15T09:00:00Z",
        status: "published",
        is_implemented: false,
        slug: "seminar-nasional-ai-industri-5",
        cover_image: null,
        carousel_images: [],
        galler_image: [],
        location: "Aula Utama UBSI Sukabumi",
        time_filter: "upcoming",
    },
    {
        id: "evt-3",
        title: "Lomba Desain UI/UX: Interface Design Challenge 2025",
        description:
            "Kompetisi desain antarmuka pengguna yang menantang peserta untuk menciptakan solusi digital inovatif. Hadiah total senilai Rp 15.000.000 menanti pemenang. Terbuka bagi pelajar SMA/SMK dan mahasiswa seluruh Indonesia.",
        start_date: "2025-06-13T10:00:00Z",
        end_date: "2025-06-13T17:00:00Z",
        published_at: "2025-05-20T09:00:00Z",
        status: "published",
        is_implemented: true,
        slug: "lomba-desain-uiux-interface-design-challenge-2025",
        cover_image: null,
        carousel_images: [],
        galler_image: [],
        location: "Online (Virtual Event)",
        time_filter: "past",
    },
    {
        id: "evt-4",
        title: "Bakti Sosial & Literasi Digital di Desa Cibeureum",
        description:
            "Program pengabdian masyarakat HIMA-IF berupa kunjungan ke Desa Cibeureum untuk mengadakan pelatihan literasi digital bagi warga desa. Kegiatan ini mencakup pengenalan internet sehat, penggunaan aplikasi produktivitas, dan sosialisasi keamanan digital.",
        start_date: "2025-05-10",
        end_date: "2025-05-10",
        published_at: "2025-04-25T09:00:00Z",
        status: "published",
        is_implemented: true,
        slug: "bakti-sosial-literasi-digital-desa-cibeureum",
        cover_image: null,
        carousel_images: [],
        galler_image: [],
        location: "Desa Cibeureum, Sukabumi",
        time_filter: "past",
    },
    {
        id: "evt-5",
        title: "Malam Keakraban (MAKRAB) HIMA-IF 2025: Nusantara Night",
        description:
            "Malam Keakraban tahunan HIMA-IF dengan tema Nusantara Night. Sebuah malam penuh keceriaan yang mempererat tali persaudaraan antar anggota melalui berbagai penampilan budaya, games, dan penghargaan anggota berprestasi tahun ini.",
        start_date: "2025-04-25",
        end_date: "2025-04-26",
        published_at: "2025-04-01T09:00:00Z",
        status: "published",
        is_implemented: true,
        slug: "makrab-hima-if-2025-nusantara-night",
        cover_image: null,
        carousel_images: [],
        galler_image: [],
        location: "Bumi Perkemahan Sukabumi",
        time_filter: "past",
    },
];
